### ISSUE TITLE
Post page (default)

### ISSUE THREAD

**Issue by WillMorrisJulien** [greenpeace/planet4-presentation-layer#105]
To answer readability issues with regard to the white heading type. I created a modification to the css style. 

 - [x] Heading : #000000
 - [x] Body, Author, Sub heading : #1a1a1a
 - [x] Hashtag : #e51538
 - [x] The top gradient overlay is at : 30% alpha/transparency 
 - [x] Gradient start colour : #074365 end colour is #FFFFFF (alpha 0%)
 - [x] The background image is at : 30% alpha/transparency 

The design files are here - https://drive.google.com/open?id=1CgB0_MoEOYdm7CYZuHe5VzGYBb-8pFP6

**Comment by Kluny** [comment]
This change does improve readability of the body text, but tags still quite hard to read. May I suggest yellow for the tags that are now in red, and use the red for the #saveourtuna hashtag (in screenshot), as well as increasing the font weight and size?

![screen shot 2017-12-13 at 14 11 19](https://user-images.githubusercontent.com/310102/33966494-a5ae645a-e014-11e7-9195-1146453b7bb9.png)

**Comment by WillMorrisJulien** [comment]
Hi Kluny, The 'Take action cover' block is a separate block and has been done. This piece of work is just for the main page (The background, overlay, body copy, Title and header tags). Which it looks like you have done. :)

**Comment by mikeselander** [comment]
Are you happy for this to be closed out then @WillMorrisJulien?

**Comment by WillMorrisJulien** [comment]
I think so. Is there a link for me to review?
