### ISSUE TITLE
Post page / Header

### ISSUE THREAD

**Issue by viniromualdo** [greenpeace/planet4-presentation-layer#117]
On link (in hot pink) above the top title, substitute "content type" info (POST • ...) by "article type" info (i.e.: STORY • ...)

It should still be linked and clicking on it take the users to a refined search result page with the "article type" filter applied to it.

Remember there's only 3 article types: Press release, Story and Publication.
Here's a mocked up example:
![header_postsxl](https://user-images.githubusercontent.com/12191933/34020464-9aac3872-e134-11e7-8fb5-0b54736f479c.png)

cc @tolen @mcshanea

**Comment by mikeselander** [comment]
Hey @viniromualdo did you mean to open this against the [Theme repo](https://github.com/greenpeace/planet4-master-theme)?

**Comment by viniromualdo** [comment]
Sorry @mikeselander I missed you comment here. I'm closing this issue here but I've re-opened it in master-theme, so our devs will take care of it! Thanks
