### ISSUE TITLE
Slick slider issue in Publications

### ISSUE THREAD

**Issue by angtheod** [greenpeace/planet4-presentation-layer#129]
Hello all, slick slider does not show up well in Content Four Column block (Publications). See [here](https://dev.p4.greenpeace.org/international/tag/fix-food/).
This appeared after applying these JS [changes](https://github.com/greenpeace/planet4-presentation-layer/pull/103/files#diff-8db7fbd6ca8e39de39a775fb7785c346R155) on settings of the slick slider

**Comment by angtheod** [comment]
No idea who to assign this to, so I'll leave it to you guys :)

**Comment by kirdia** [comment]
Fixed with this [PR](https://github.com/greenpeace/planet4-master-theme/pull/156)
