### ISSUE TITLE
Maybe Remove Built Files

### ISSUE THREAD

**Issue by mikeselander** [greenpeace/planet4-presentation-layer#32]
**Question for all:**
Are the static, built CSS & JS files used, beyond styling the local site for testing?

We have several built files in the repo - this is generally considered bad practice as merge conflicts are more likely, and keeping track of the source files only and building files as a part of the deploy process is cleaner. Additionally, it mucks up diff rates and means that git always thinks that there is always changes on even the smallest modification.

However, I don't want to accidentally mess up an existing deploy process or workflow if there is one.

**Comment by 27Bslash6** [comment]
Good question, at what point are these files integrated into the master theme?
