### ISSUE TITLE
Issue page Browser Testing

### ISSUE THREAD

**Issue by mikeselander** [greenpeace/planet4-presentation-layer#44]
All tested on Chrome 

**Overall:**
 - Missing Happy action box
 - Missing "In the News" block
 - Lots of all-caps text - CSS should be handling all-caps, the text in the DOM should be appropriately capitalized
 - I was told that yellow share buttons were being replaced by Share This and to get rid of all yellow-button styles. 
 - Whole campaign blocks should link imo
 - Publications aren't linking at all

**Mobile:**
 - Publications laid out wrong
 - Our campaigns laid out wrong
 - Buttons in header shouldn't show on mobile according to designs (conflicts with Act Header design though - should probably only choose one)
Video is suppoed to go all the way to the window edges
 - Spacing around section titles needs to be smoother out - the vertical rhythm is off

**Medium:**
 - 485px - 783px the 3-column striped layout is broken
 - Font sizes are generally off from what the designs are

**Comment by alexcavender** [comment]
@mikeselander What is the Happy action box?

**Comment by mikeselander** [comment]
@alexcavender the action alert section at the end of the page:

![screen shot 2017-11-28 at 2 54 59 pm](https://user-images.githubusercontent.com/3021494/33348681-252895ae-d44c-11e7-81a1-0637a50c835a.png)

**Comment by alexcavender** [comment]
@mikeselander Thank you! perfecto

**Comment by alexcavender** [comment]
- [ ] Add Happy Action block

**Comment by koyan** [comment]
@alexcavender and @mikeselander 
The happy action box has been replaced by action fields. The latest designs can be seen at: 
https://jira.greenpeace.org/browse/PLANET-1398?jql=text%20~%20%22engaging%20network%20fields%22%20and%20project%20%3D%20Planet4%20

Currently this has been implemented with an iframed form from the vendor: (check bottom of page of: http://dev.p4.greenpeace.org/ ) 
At a later stage (months down the line) we will see if we can add the form fields directly using the vendor's API. But for all practical purposes now, the best we can use is the iframe as you see it. 
We do have the ability to make minor changes in the css of the form itself (in the vendor side), and we have done that to make the form responsive.

**Comment by koyan** [comment]
It was decided by the product owner that since we are using the form directly, we are dropping the action box functionality

**Comment by alexcavender** [comment]
@koyan Thanks I will implement the iFrame here

**Comment by alexcavender** [comment]
@mikeselander This might also be a question for @koyan 
The Static four column block on mobile appears to be a Slideshow -- is there already an approved slider library like FlexSlider or Slick Slider that I should use for this?
Thanks

**Comment by ashish173** [comment]
@alexcavender so far we have not used any libs as such, I have used the bootstrap carousel so far.

**Comment by alexcavender** [comment]
@ashish173 Ok thank you

**Comment by ashish173** [comment]
@alexcavender regarding your comment for implementing iFrame, it has already been done. Please chat with me if there is any confusion.

**Comment by mikeselander** [comment]
@alexcavender can we now close this PR since #52 is merged?
