### ISSUE TITLE
Home page review

### ISSUE THREAD

**Issue by viniromualdo** [greenpeace/planet4-presentation-layer#60]
Hey all, I'll be posting reviews for each screen size of Home here. So far I got for you S and XL sizes. 
I screenshoted the published page and added comments in the pdf directly to make it as straight-forward as possible. Whoever will be taking this down (as assigned by Adrian) please see the attached files.
[Home_S.pdf](https://github.com/greenpeace/planet4-presentation-layer/files/1521705/Home_S.pdf)
[HomeXL.pdf](https://github.com/greenpeace/planet4-presentation-layer/files/1521706/HomeXL.pdf)

There's been a few design updates to it (mostly color and font-sizes). Latest master file and exported screens have been uploaded to [Drive](https://drive.google.com/drive/u/0/folders/0B-hrpY3C01WJaFhEYjlPeE52MkU).

Any questions, I'd suggest reaching out directly to me in Rocketchat, that's the quickest way. Cheers!

**Comment by ashish173** [comment]
@viniromualdo this is not the latest design which I have pushed in the `gh-pages` branch for the final review. I see the background colour as green, which I had removed in favour of new gradient. We need to figure out the correct merge for `home_page_2`.

**Comment by ashish173** [comment]
@viniromualdo @mcshanea for XL I have done all these fixes, just need to fix the merge issue.

**Comment by viniromualdo** [comment]
@ashish173 are they published in presentation layer? Right now I don't see these fixes in XL.

**Comment by viniromualdo** [comment]
Second round of review on home_S
[Home_S_v2.pdf](https://github.com/greenpeace/planet4-presentation-layer/files/1530976/Home_S_v2.pdf)

for happy point comment in pdf, refer to this image 
![happypoint_s](https://user-images.githubusercontent.com/12191933/33605214-0af8f9d6-d9b9-11e7-90fb-df569f51af61.jpg)

**Comment by viniromualdo** [comment]
More tweaks for all sizes:
- credit color should be #666666
- the background behind the caption on the middle carousel should be dynamic (increase/decrease accordingly with lines of text)

**Comment by ashish173** [comment]
@viniromualdo I'll be changing the colour in the branch(point 1), also changing the behaviour of the caption, 

For third request, I have created an issue #76 and it will done in a separate PR.

**Comment by viniromualdo** [comment]
Reviews on home_L, out of the oven @ashish173  
[home_L_v2.pdf](https://github.com/greenpeace/planet4-presentation-layer/files/1535502/home_L_v2.pdf)

**Comment by viniromualdo** [comment]
Reviews on home_M ready, @ashish173 
[home_M.pdf](https://github.com/greenpeace/planet4-presentation-layer/files/1542139/home_M.pdf)

**Comment by mikeselander** [comment]
I've gone through several blocks on this page and fixed what is still pertinent, but quite a bit is out of date at this point. I would recommend merging what we have fixed, and then having you co back through the site @viniromualdo.

The pending fixes are #110, #118 #123, #124, and #125.

**Comment by mikeselander** [comment]
The only blocker on this issue is #110 which I expect to be closed shortly.

I'm going to mark that PR as auto-closing this issue and we can harvest additional homepage feedback in future issues.
