### ISSUE TITLE
Buttons at content two column don't have a target url

### ISSUE THREAD

**Issue by koyan** [greenpeace/planet4-presentation-layer#65]
https://github.com/greenpeace/planet4-presentation-layer/blob/revert_home_page/home.html#L802
` <button class="btn btn-light-blue btn-normal">Explore the issues</button>`
Where do we put the target url in this markup?

**Comment by mikeselander** [comment]
@koyan `<button>`s aren't generally intended for linking - this should probably be an `<a>` tag instead.

**Comment by koyan** [comment]
@mikeselander we have already changed it to <a> tag. We should have closed this issue.
