### ISSUE TITLE
ACT / Covers

### ISSUE THREAD

**Issue by WillMorrisJulien** [greenpeace/planet4-presentation-layer#68]
Hey all, I'll be posting reviews for Act covers here.

**Comment by WillMorrisJulien** [comment]
There appears to be a problem with Chrome loading the responsive content CSS. This leads to the content font not resizing for M and S. See attached image. 
![small_size_font_anomaly](https://user-images.githubusercontent.com/34244772/33606001-d4f904b6-d9b3-11e7-8fea-06838cac211c.jpg)

**Comment by WillMorrisJulien** [comment]
Hash tag above the cover title is incorrect in passive state. It should have no left padding. See roll-over state to see the correct placement.

**Comment by WillMorrisJulien** [comment]
There appears to be anomaly in the breakpoints. We get a strange formatting issue between M & L (See image) and between S & L (see image). We need for it to go straight from L to M and then from M to S. Without any variations between.
![cover_betweetn_s m](https://user-images.githubusercontent.com/34244772/33606359-23ab48c0-d9b5-11e7-8b12-2edce7cca881.jpg)
![cover_betweetn_m l](https://user-images.githubusercontent.com/34244772/33606360-23c687b6-d9b5-11e7-8ba3-9f157cca93a0.jpg)

**Comment by WillMorrisJulien** [comment]
Roll over for non evergreen cover's (these covers shown) should be 50% #ffffff not green.

**Comment by WillMorrisJulien** [comment]
Type size and colour for roll over state of Take Action covers should be as follows - 
For L & XL the heading : 1.75rem colour : #191919
For L & XL the body text : 1.125rem colour : #191919 Line height : 1.6

The style sheet for Small and Medium are not loading however they should be - 
For S & M the heading : 1.5rem colour : #191919
For S & M the body text : 1rem colour : #191919  Line height : 1.3

Please not that the evergreen typographic sizes should be the same.

**Comment by mikeselander** [comment]
@WillMorrisJulien can we talk about these changes when you're on? I'm not clear on some of this feedback.
