### ISSUE TITLE
Issue page / Campaign thumbnail block

### ISSUE THREAD

**Issue by sagarsdeshmukh** [greenpeace/planet4-presentation-layer#69]
Hi

In campaign thumbnail block - I see a href attribute inside span element

 `<span class="yellow-cta" href="#">`

why is this inside span element ?

**Comment by mikeselander** [comment]
Good catch @sagarsdeshmukh those shouldn't have the `href` attribute and the whole block has an `a` around it. We're removing the attributes from the markup.
