### ISSUE TITLE
Remove all letter spacing properties

### ISSUE THREAD

**Issue by ashish173** [greenpeace/planet4-presentation-layer#76]
@viniromualdo has requested in #60 to remove the letter spacings of all sorts, creating an issue and a new PR should follow for this change.

cc: @mikeselander @pdewouters @mcshanea

**Comment by mikeselander** [comment]
I just did a whole-project search and couldn't find any instances of `letter-spacing` being used. I remove the `h1` style in #54 so I believe that this is complete.
