### ISSUE TITLE
Issues page / Breakpoint problems

### ISSUE THREAD

**Issue by viniromualdo** [greenpeace/planet4-presentation-layer#85]
For blocks in Issue's page there are a few odd breakpoints that should not exist like at:
- 1024px
- 1200px
- 1538px

I believe we defined our breakpoints as:
S: up to 768px
M: up to 992px
L: up to 1480px
XL: >1480px

**Comment by WillMorrisJulien** [comment]
There extra break points in Act as well. I flagged those up earlier this week.

**Comment by mikeselander** [comment]
I will take this on and remove any extraneous breakpoints used in the codebase.

**Comment by mikeselander** [comment]
FYI I've removed the `1024`, `1200`, and `1538` breakpoints in #90 but am keeping an extra smaller breakpoint of `575` around as we have a need for a smaller, intermediate styleset.

**Comment by viniromualdo** [comment]
fantastic, thanks!
